language: node_js
sudo: false
node_js:
  - "6.2"
  - "4.3"
before_script:
  - npm install -g grunt-cli bower
  - bower install
after_script: NODE_ENV=test YOURPACKAGE_COVERAGE=1 mocha test --require blanket --reporter mocha-lcov-reporter --recursive | ./node_modules/coveralls/bin/coveralls.js
